### ISSUE TITLE
Set context path

### ISSUE THREAD

**Issue by matheusgr** [gabrielguim/pharmaweb#16]
https://github.com/gabrielguim/pharmaweb/blob/e3406e8e90a760f5507957645e7c001bc67a2362/pharmaweb/src/main/kotlin/com/pharmaweb/pharmaweb/routing/DruggistRouting.kt#L10

the "/api" resource path is called a context path. one should avoid to set it during the request mapping. if i need to set the mapping to /api_v1 or /api_v2 it would be hard to do so in your application.

you can use the contextPath server property (see app configuration) as follow:

`server.contextPath=/api`

**Comment by gabrielguim** [comment]
Oh, cool. I didn't know that.

Thanks for the advice again.
