### ISSUE TITLE
Data set initialization

### ISSUE THREAD

**Issue by matheusgr** [gabrielguim/pharmaweb#17]
https://github.com/gabrielguim/pharmaweb/blob/e3406e8e90a760f5507957645e7c001bc67a2362/pharmaweb/src/main/kotlin/com/pharmaweb/pharmaweb/routing/ProductRouting.kt#L20

I understand that this was used to start demo data to your application. You can also set a data.sql that is invoked for default for your application:

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-initialize-a-database-using-spring-jdbc

That way you can have your test data but also your application running as is.

Also, probably the service would be a better place to do such initialization.

You may ignore this issue :) is just fyi.

**Comment by gabrielguim** [comment]
Thank you for the advice, @matheusgr! 

I have moved the mock data to the ProductService! 😄
